/oak:
  ros__parameters:
    camera:
      i_pipeline_type: "RGB"
    rgb:
      i_enable_preview: true
    nn:
      i_enable_passthrough: false
      i_nn_config_path: "/cika_ws/src/cika_perception/models/300_epoch_best.json"
      i_disable_resize: false
    stereo:
      i_align_depth: true