controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    skid_steer_controller:
      type: diff_drive_controller/DiffDriveController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

skid_steer_controller:
  ros__parameters:
    left_wheel_names: ["left_front_wheel_1_joint", "left_back_wheel_1_joint"]
    right_wheel_names: ["right_front_wheel_1_joint", "right_back_wheel_1_joint"]
    wheel_separation: 0.363
    wheel_radius: 0.0885
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    open_loop: false
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    use_sim_time: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 20.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 4.0
        has_acceleration_limits: true
        max_acceleration: 25.0

arm_controller:
  ros__parameters:
    joints:
      - turntable_1_joint
      - lower_arm_1_joint
      - center_arm_1_joint
      - upper_arm_1_joint
      - gripper_mount_1_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    use_sim_time: true

gripper_controller:
  ros__parameters:
    joints:
      - left_gripper_1_joint
      - right_gripper_1_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    use_sim_time: true
